# Generated by Django 3.2.12 on 2022-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2000)),
                ('isOpened', models.BooleanField(default=False)),
                ('fromUser', models.CharField(max_length=200)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igoMaster.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=2000)),
                ('isOpened', models.BooleanField(default=False)),
                ('fromUser', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igoMaster.user')),
            ],
        ),
    ]
