# Generated by Django 3.2.12 on 2022-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablishmenttype',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='etablishmenttype',
            name='image',
            field=models.CharField(default='AUCUNE IMAGE', max_length=150),
        ),
    ]
