# Generated by Django 3.2.12 on 2022-09-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0004_auto_20220901_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='FRANCE', max_length=250),
        ),
        migrations.AddField(
            model_name='etablishment',
            name='postal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='tiktokName',
            field=models.CharField(default='Non renseigné', max_length=500),
        ),
        migrations.AlterField(
            model_name='social',
            name='tweeterName',
            field=models.CharField(default='Non renseigné', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='isActiive',
            field=models.BooleanField(default=False),
        ),
    ]
