# Generated by Django 3.2.12 on 2022-09-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0005_auto_20220902_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablishment',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OTHER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('etablishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igoMaster.etablishment')),
            ],
        ),
    ]
