# Generated by Django 3.2.12 on 2022-09-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0006_auto_20220907_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField(default=25)),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(default=1)),
                ('fee', models.FloatField(default=0.0)),
                ('stopDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('etablishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igoMaster.etablishment')),
            ],
        ),
    ]
