# Generated by Django 3.2.12 on 2022-09-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0007_forfait_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='text',
            field=models.CharField(default='Non renseigné', max_length=2000),
        ),
    ]
