# Generated by Django 3.2.12 on 2022-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0008_promotion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmail',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
