# Generated by Django 3.2.12 on 2022-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0009_alter_contactmail_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmail',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
