# Generated by Django 3.2.12 on 2022-11-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igoMaster', '0010_alter_contactmail_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.ImageField(blank=True, default='blank-dark.svg', null=True, upload_to=''),
        ),
    ]
